# Puerto de la aplicaci\u00f3n
server.port=8080

# Nombre de la aplicaci\u00f3n
spring.application.name=moto-racer-x

# Mostrar errores detallados (solo durante desarrollo)
server.error.include-message=always
server.error.include-binding-errors=always

# Configuraci\u00f3n Thymeleaf (si usas templates)
spring.thymeleaf.cache=false